// <auto-generated />
namespace WebBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class WebBlog20160803 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WebBlog20160803));
        
        string IMigrationMetadata.Id
        {
            get { return "201608110900418_WebBlog-20160803"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
